name: ado_downscaler
channels:
    - conda-forge
dependencies:
    - esmpy==8.1.1
    - xarray==0.19.0
    - scipy==1.7.1
    - statsmodels==0.12.2
    - dask==2021.9.1
    - netCDF4==1.5.7
    - bottleneck==1.3.2
    - cfgrib==0.9.9.0
    - pip==21.0
    - pathlib==1.0.1
    - click==7.1.2
    - pip:
        - cdsapi==0.5.1
        - git+https://github.com/pangeo-data/xesmf.git
        - git+https://github.com/geoase/ado-downloader.git
        - git+https://github.com/geoase/ado-downscaler.git
